### ISSUE TITLE
ClassCastException: LayoutParams cannot be cast to MarginLayoutParams : FlowLayout.onMeasure(FlowLayout.java:60))

### ISSUE THREAD

**Issue by analytic-bias** [lankton/android-flowlayout#3]
I'm not sure about which method invoking throws this exception, because the only stack trace that doesn't belong to Android System API is `FlowLayout.onMeasure(FlowLayout.java:60)`.  
And this is the list of methods of FlowLayout that I invoked before the exception was thrown by FlowLayout:  
1. addView
2. removeView
3. removeAllViews
4. relayoutToCompressAndAlign (I think this is irrelevant because I invoke this method in another Activity but for precaution, I list it, too.)

And the line of Flowlayout.java that throws this exception is:
`measureChildWithMargins(child, widthMeasureSpec, 0, heightMeasureSpec, lineY);` .  
And I append the exception stack trace from the system:
`05-04 16:10:47.192 3294-3294/club.ersao.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: club.ersao.app, PID: 3294
                                                              java.lang.ClassCastException: android.view.ViewGroup$LayoutParams cannot be cast to android.view.ViewGroup$MarginLayoutParams
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5942)
                                                                  at cn.lankton.flowlayout.FlowLayout.onMeasure(FlowLayout.java:60)
                                                                  at android.view.View.measure(View.java:18788)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                  at android.view.View.measure(View.java:18788)
                                                                  at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1283)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                  at android.widget.ScrollView.onMeasure(ScrollView.java:340)
                                                                  at android.view.View.measure(View.java:18788)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                  at android.view.View.measure(View.java:18788)
                                                                  at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1560)
                                                                  at android.view.View.measure(View.java:18788)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                  at android.view.View.measure(View.java:18788)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                  at android.view.View.measure(View.java:18788)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                  at android.view.View.measure(View.java:18788)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                  at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                  at android.view.View.measure(View.java:18788)
                                                                  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                                  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1191)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by lankton** [comment]
Got it.
To fix that, I overwrited generateDefaultLayoutParams and added some judgements before LayoutParams being used as MarginLayoutParam.
Now, I think this bug is fixed and expect your feedback.
Thanks for your issue, it's helpful. ^_^

**Comment by analytic-bias** [comment]
Yes, actually, I didn't pass a MarginLayoutParam parameter while invoking method addView.
And you've fix it.
And there's another suggestion: You should upload your library to the Bintray. If you do that, when other people want to use your library, they can simply add a statement, `compile XXX` to the `dependencies` closure of their Gradle Build Script.
And here's the Gradle Plugin that you need when you want to upload your library to the Bintray:
[Gradle Bintray Plugin](https://bintray.com/jfrog/jfrog-jars/gradle-bintray-plugin)

**Comment by analytic-bias** [comment]
I guess you can close this issue now.
